/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAminoChainAuthenticator__factory } from "./IAminoChainAuthenticator__factory";
export { IAminoChainDonation__factory } from "./IAminoChainDonation__factory";
export { IAminoChainMarketplace__factory } from "./IAminoChainMarketplace__factory";
