/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface MockAminoChainMarketplaceInterface extends utils.Interface {
  functions: {
    "buyItem(uint256)": FunctionFragment;
    "cancelListing(uint256)": FunctionFragment;
    "listItem(uint256,address,address)": FunctionFragment;
    "setAuthenticatorAddress(address)": FunctionFragment;
    "setDonorIncentiveRate(uint256)": FunctionFragment;
    "setTokenizedStemCells(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateListing(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "buyItem"
      | "cancelListing"
      | "listItem"
      | "setAuthenticatorAddress"
      | "setDonorIncentiveRate"
      | "setTokenizedStemCells"
      | "transferOwnership"
      | "updateListing"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buyItem",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelListing",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "listItem",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthenticatorAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setDonorIncentiveRate",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenizedStemCells",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateListing",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "buyItem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listItem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthenticatorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDonorIncentiveRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenizedStemCells",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateListing",
    data: BytesLike
  ): Result;

  events: {
    "authenticatorAddressSet(address)": EventFragment;
    "listingCanceled(address,uint256)": EventFragment;
    "newDonorIncentiveRate(uint256)": EventFragment;
    "newListing(address,uint256,uint256,address,address)": EventFragment;
    "ownershipTransferred(address,address)": EventFragment;
    "sale(address,uint256,address,uint256,uint256,address,uint256,address)": EventFragment;
    "stemCellsAddressSet(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "authenticatorAddressSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "listingCanceled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "newDonorIncentiveRate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "newListing"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ownershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "sale"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "stemCellsAddressSet"): EventFragment;
}

export interface authenticatorAddressSetEventObject {
  authenticator: string;
}
export type authenticatorAddressSetEvent = TypedEvent<
  [string],
  authenticatorAddressSetEventObject
>;

export type authenticatorAddressSetEventFilter =
  TypedEventFilter<authenticatorAddressSetEvent>;

export interface listingCanceledEventObject {
  seller: string;
  tokenId: BigNumber;
}
export type listingCanceledEvent = TypedEvent<
  [string, BigNumber],
  listingCanceledEventObject
>;

export type listingCanceledEventFilter = TypedEventFilter<listingCanceledEvent>;

export interface newDonorIncentiveRateEventObject {
  newIncentiveRate: BigNumber;
}
export type newDonorIncentiveRateEvent = TypedEvent<
  [BigNumber],
  newDonorIncentiveRateEventObject
>;

export type newDonorIncentiveRateEventFilter =
  TypedEventFilter<newDonorIncentiveRateEvent>;

export interface newListingEventObject {
  seller: string;
  tokenId: BigNumber;
  price: BigNumber;
  donor: string;
  bioBank: string;
}
export type newListingEvent = TypedEvent<
  [string, BigNumber, BigNumber, string, string],
  newListingEventObject
>;

export type newListingEventFilter = TypedEventFilter<newListingEvent>;

export interface ownershipTransferredEventObject {
  oldOwner: string;
  newOwner: string;
}
export type ownershipTransferredEvent = TypedEvent<
  [string, string],
  ownershipTransferredEventObject
>;

export type ownershipTransferredEventFilter =
  TypedEventFilter<ownershipTransferredEvent>;

export interface saleEventObject {
  seller: string;
  tokenId: BigNumber;
  buyer: string;
  salePrice: BigNumber;
  protocolFee: BigNumber;
  donor: string;
  donorIncentive: BigNumber;
  bioBank: string;
}
export type saleEvent = TypedEvent<
  [string, BigNumber, string, BigNumber, BigNumber, string, BigNumber, string],
  saleEventObject
>;

export type saleEventFilter = TypedEventFilter<saleEvent>;

export interface stemCellsAddressSetEventObject {
  stemCells: string;
}
export type stemCellsAddressSetEvent = TypedEvent<
  [string],
  stemCellsAddressSetEventObject
>;

export type stemCellsAddressSetEventFilter =
  TypedEventFilter<stemCellsAddressSetEvent>;

export interface MockAminoChainMarketplace extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockAminoChainMarketplaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buyItem(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cancelListing(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    listItem(
      tokenId: PromiseOrValue<BigNumberish>,
      donor: PromiseOrValue<string>,
      bioBank: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAuthenticatorAddress(
      _authenticator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDonorIncentiveRate(
      newIncentiveRate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setTokenizedStemCells(
      stemCells: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateListing(
      tokenId: PromiseOrValue<BigNumberish>,
      newPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  buyItem(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cancelListing(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  listItem(
    tokenId: PromiseOrValue<BigNumberish>,
    donor: PromiseOrValue<string>,
    bioBank: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAuthenticatorAddress(
    _authenticator: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDonorIncentiveRate(
    newIncentiveRate: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setTokenizedStemCells(
    stemCells: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateListing(
    tokenId: PromiseOrValue<BigNumberish>,
    newPrice: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buyItem(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelListing(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    listItem(
      tokenId: PromiseOrValue<BigNumberish>,
      donor: PromiseOrValue<string>,
      bioBank: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setAuthenticatorAddress(
      _authenticator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setDonorIncentiveRate(
      newIncentiveRate: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setTokenizedStemCells(
      stemCells: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateListing(
      tokenId: PromiseOrValue<BigNumberish>,
      newPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "authenticatorAddressSet(address)"(
      authenticator?: null
    ): authenticatorAddressSetEventFilter;
    authenticatorAddressSet(
      authenticator?: null
    ): authenticatorAddressSetEventFilter;

    "listingCanceled(address,uint256)"(
      seller?: null,
      tokenId?: null
    ): listingCanceledEventFilter;
    listingCanceled(seller?: null, tokenId?: null): listingCanceledEventFilter;

    "newDonorIncentiveRate(uint256)"(
      newIncentiveRate?: null
    ): newDonorIncentiveRateEventFilter;
    newDonorIncentiveRate(
      newIncentiveRate?: null
    ): newDonorIncentiveRateEventFilter;

    "newListing(address,uint256,uint256,address,address)"(
      seller?: null,
      tokenId?: null,
      price?: null,
      donor?: null,
      bioBank?: null
    ): newListingEventFilter;
    newListing(
      seller?: null,
      tokenId?: null,
      price?: null,
      donor?: null,
      bioBank?: null
    ): newListingEventFilter;

    "ownershipTransferred(address,address)"(
      oldOwner?: null,
      newOwner?: null
    ): ownershipTransferredEventFilter;
    ownershipTransferred(
      oldOwner?: null,
      newOwner?: null
    ): ownershipTransferredEventFilter;

    "sale(address,uint256,address,uint256,uint256,address,uint256,address)"(
      seller?: null,
      tokenId?: null,
      buyer?: null,
      salePrice?: null,
      protocolFee?: null,
      donor?: null,
      donorIncentive?: null,
      bioBank?: null
    ): saleEventFilter;
    sale(
      seller?: null,
      tokenId?: null,
      buyer?: null,
      salePrice?: null,
      protocolFee?: null,
      donor?: null,
      donorIncentive?: null,
      bioBank?: null
    ): saleEventFilter;

    "stemCellsAddressSet(address)"(
      stemCells?: null
    ): stemCellsAddressSetEventFilter;
    stemCellsAddressSet(stemCells?: null): stemCellsAddressSetEventFilter;
  };

  estimateGas: {
    buyItem(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cancelListing(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    listItem(
      tokenId: PromiseOrValue<BigNumberish>,
      donor: PromiseOrValue<string>,
      bioBank: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAuthenticatorAddress(
      _authenticator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDonorIncentiveRate(
      newIncentiveRate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setTokenizedStemCells(
      stemCells: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateListing(
      tokenId: PromiseOrValue<BigNumberish>,
      newPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyItem(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cancelListing(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    listItem(
      tokenId: PromiseOrValue<BigNumberish>,
      donor: PromiseOrValue<string>,
      bioBank: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAuthenticatorAddress(
      _authenticator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDonorIncentiveRate(
      newIncentiveRate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setTokenizedStemCells(
      stemCells: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateListing(
      tokenId: PromiseOrValue<BigNumberish>,
      newPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
