/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAminoChainAuthenticator } from "./IAminoChainAuthenticator";
export type { IAminoChainDonation } from "./IAminoChainDonation";
export type { IAminoChainMarketplace } from "./IAminoChainMarketplace";
