/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAminoChainAuthenticator } from "./IAminoChainAuthenticator";
export type { IAminoChainMarketplace } from "./IAminoChainMarketplace";
export type { IDonationNFT } from "./IDonationNFT";
