/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IConsumer, IConsumerInterface } from "../../contracts/IConsumer";

const _abi = [
  {
    inputs: [],
    name: "bonusToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "marketing",
        type: "uint256",
      },
    ],
    name: "buyOutside",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IConsumer__factory {
  static readonly abi = _abi;
  static createInterface(): IConsumerInterface {
    return new utils.Interface(_abi) as IConsumerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IConsumer {
    return new Contract(address, _abi, signerOrProvider) as IConsumer;
  }
}
